import sharp from "sharp";
import fs from "fs";
import path from "path";

const WIDTHS = [480, 768, 960, 1440];
const QUALITY = 90;
const BLOGS_DIR = "public/blogs";
const MANIFEST_PATH = "src/generated/image-manifest.ts";
const SUPPORTED = [".png", ".jpg", ".jpeg"];

function findImages(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findImages(full));
    } else if (SUPPORTED.includes(path.extname(entry.name).toLowerCase())) {
      // Skip files that are already optimized variants
      if (!/-\d+\.webp$/.test(entry.name)) results.push(full);
    }
  }
  return results;
}

async function run() {
  fs.mkdirSync("src/generated", { recursive: true });

  const images = findImages(BLOGS_DIR);
  const manifest = {};

  for (const imgPath of images) {
    const { dir, name, ext } = path.parse(imgPath);
    const meta = await sharp(imgPath).metadata();
    const originalWidth = meta.width ?? 0;

    // Public URL key (e.g. /blogs/slug/image.png) — strip "public" prefix
    const publicKey = "/" + imgPath.replace(/\\/g, "/").replace(/^public\//, "");

    const generatedWidths = [];

    for (const w of WIDTHS) {
      if (w > originalWidth) continue; // don't upscale

      const outFile = path.join(dir, `${name}-${w}.webp`);
      if (!fs.existsSync(outFile)) {
        await sharp(imgPath)
          .resize(w, null)
          .webp({ quality: QUALITY })
          .toFile(outFile);
        console.log(`✓ ${outFile}`);
      } else {
        console.log(`- ${outFile} (skip, exists)`);
      }
      generatedWidths.push(w);
    }

    // Always include original width as largest entry
    if (!generatedWidths.includes(originalWidth)) {
      generatedWidths.push(originalWidth);
    }

    manifest[publicKey] = {
      widths: generatedWidths.sort((a, b) => a - b),
      base: "/" + path.join(dir, name).replace(/\\/g, "/").replace(/^public\//, ""),
      ext,
    };
  }

  const content = `// Auto-generated by scripts/optimize-images.mjs — do not edit manually
export const imageManifest: Record<string, { widths: number[]; base: string; ext: string }> = ${JSON.stringify(manifest, null, 2)};
`;

  fs.writeFileSync(MANIFEST_PATH, content);
  console.log(`\n✓ Manifest written to ${MANIFEST_PATH}`);
}

run().catch(console.error);
